server:
  port: 9010

spring:
  application:
    name: "delivery"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  cloud:
    function:
      definition: completeDelivery
    stream:
      bindings:
        completeDelivery-in-0:
          destination: order-to-delivery
          group: ${spring.application.name}
        completeDelivery-out-0:
          destination: delivery-to-order
      kafka:
        binder:
          brokers:
            - localhost:9092