server:
  port: 9010

spring:
  application:
    name: "delivery"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  cloud:
    function:
      definition: createDelivery
    stream:
      bindings:
        createDelivery-in-0:
          destination: send-communication
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s